// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518224731_fixedSeededRequests")]
    partial class fixedSeededRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountRole", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("AccountId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccountRole", (string)null);

                    b.HasData(
                        new
                        {
                            AccountId = new Guid("aaaaaaaa-3333-3333-3333-333333333333"),
                            RoleId = new Guid("aaaaaaaa-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            AccountId = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            RoleId = new Guid("aaaaaaaa-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            AccountId = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            RoleId = new Guid("bbbbbbbb-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            AccountId = new Guid("cccccccc-3333-3333-3333-333333333333"),
                            RoleId = new Guid("bbbbbbbb-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            AccountId = new Guid("dddddddd-3333-3333-3333-333333333333"),
                            RoleId = new Guid("cccccccc-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApproverProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApproverProfileId");

                    b.HasIndex("RegionId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-3333-3333-3333-333333333333"),
                            Login = "john.doe",
                            Name = "John Doe",
                            Password = "hashed_password_1",
                            RegionId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            ApproverProfileId = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            Login = "jane.smith",
                            Name = "Jane Smith",
                            Password = "hashed_password_2",
                            RegionId = new Guid("bbbbbbbb-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-333333333333"),
                            ApproverProfileId = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Login = "peter.jones",
                            Name = "Peter Jones",
                            Password = "hashed_password_3",
                            RegionId = new Guid("cccccccc-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-3333-3333-3333-333333333333"),
                            ApproverProfileId = new Guid("cccccccc-1111-1111-1111-111111111111"),
                            Login = "admin",
                            Name = "System Admin",
                            Password = "hashed_password_4",
                            RegionId = new Guid("bbbbbbbb-cccc-cccc-cccc-cccccccccccc")
                        });
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.ApproverProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApproverProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            MaxAmount = 500m,
                            MinAmount = 0m,
                            Name = "Junior Approver"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            MaxAmount = 2000m,
                            MinAmount = 500m,
                            Name = "Senior Approver"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-1111-1111-1111-111111111111"),
                            MaxAmount = 999999m,
                            MinAmount = 2000m,
                            Name = "Executive Approver"
                        });
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RequestId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Price", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("UnitsOfMeasure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId", "RegionId");

                    b.HasIndex("RegionId");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Amount = 1200.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("bbbbbbbb-cccc-cccc-cccc-cccccccccccc"),
                            Amount = 1100.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("cccccccc-dddd-dddd-dddd-dddddddddddd"),
                            Amount = 1050.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            RegionId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Amount = 300.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            RegionId = new Guid("bbbbbbbb-cccc-cccc-cccc-cccccccccccc"),
                            Amount = 280.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            RegionId = new Guid("cccccccc-dddd-dddd-dddd-dddddddddddd"),
                            Amount = 270.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            RegionId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Amount = 45.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            RegionId = new Guid("bbbbbbbb-cccc-cccc-cccc-cccccccccccc"),
                            Amount = 40.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            RegionId = new Guid("cccccccc-dddd-dddd-dddd-dddddddddddd"),
                            Amount = 38.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            RegionId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Amount = 25.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            RegionId = new Guid("bbbbbbbb-cccc-cccc-cccc-cccccccccccc"),
                            Amount = 22.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            RegionId = new Guid("cccccccc-dddd-dddd-dddd-dddddddddddd"),
                            Amount = 20.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            RegionId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Amount = 350.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            RegionId = new Guid("bbbbbbbb-cccc-cccc-cccc-cccccccccccc"),
                            Amount = 320.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            RegionId = new Guid("cccccccc-dddd-dddd-dddd-dddddddddddd"),
                            Amount = 300.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RegionId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Amount = 400.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RegionId = new Guid("bbbbbbbb-cccc-cccc-cccc-cccccccccccc"),
                            Amount = 370.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RegionId = new Guid("cccccccc-dddd-dddd-dddd-dddddddddddd"),
                            Amount = 350.00m,
                            UnitsOfMeasure = "pcs"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Amount = 12.00m,
                            UnitsOfMeasure = "pack"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("bbbbbbbb-cccc-cccc-cccc-cccccccccccc"),
                            Amount = 10.00m,
                            UnitsOfMeasure = "pack"
                        },
                        new
                        {
                            ProductId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("cccccccc-dddd-dddd-dddd-dddddddddddd"),
                            Amount = 9.00m,
                            UnitsOfMeasure = "pack"
                        },
                        new
                        {
                            ProductId = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Amount = 8.00m,
                            UnitsOfMeasure = "pack"
                        },
                        new
                        {
                            ProductId = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("bbbbbbbb-cccc-cccc-cccc-cccccccccccc"),
                            Amount = 7.00m,
                            UnitsOfMeasure = "pack"
                        },
                        new
                        {
                            ProductId = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("cccccccc-dddd-dddd-dddd-dddddddddddd"),
                            Amount = 6.50m,
                            UnitsOfMeasure = "pack"
                        },
                        new
                        {
                            ProductId = new Guid("33333333-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Amount = 150.00m,
                            UnitsOfMeasure = "license"
                        },
                        new
                        {
                            ProductId = new Guid("33333333-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("bbbbbbbb-cccc-cccc-cccc-cccccccccccc"),
                            Amount = 140.00m,
                            UnitsOfMeasure = "license"
                        },
                        new
                        {
                            ProductId = new Guid("33333333-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("cccccccc-dddd-dddd-dddd-dddddddddddd"),
                            Amount = 135.00m,
                            UnitsOfMeasure = "license"
                        },
                        new
                        {
                            ProductId = new Guid("44444444-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Amount = 600.00m,
                            UnitsOfMeasure = "license"
                        },
                        new
                        {
                            ProductId = new Guid("44444444-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("bbbbbbbb-cccc-cccc-cccc-cccccccccccc"),
                            Amount = 560.00m,
                            UnitsOfMeasure = "license"
                        },
                        new
                        {
                            ProductId = new Guid("44444444-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("cccccccc-dddd-dddd-dddd-dddddddddddd"),
                            Amount = 540.00m,
                            UnitsOfMeasure = "license"
                        },
                        new
                        {
                            ProductId = new Guid("55555555-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Amount = 80.00m,
                            UnitsOfMeasure = "license"
                        },
                        new
                        {
                            ProductId = new Guid("55555555-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("bbbbbbbb-cccc-cccc-cccc-cccccccccccc"),
                            Amount = 75.00m,
                            UnitsOfMeasure = "license"
                        },
                        new
                        {
                            ProductId = new Guid("55555555-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RegionId = new Guid("cccccccc-dddd-dddd-dddd-dddddddddddd"),
                            Amount = 70.00m,
                            UnitsOfMeasure = "license"
                        });
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Standard business laptop for daily work use",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Description = "24-inch Full HD display",
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Description = "Wired USB office keyboard",
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Description = "Wired USB optical mouse",
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Description = "Standard office desk with cable management",
                            Name = "Desk"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Description = "Ergonomic office chair with lumbar support",
                            Name = "Chair"
                        },
                        new
                        {
                            Id = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "A5 lined notebook, pack of 3",
                            Name = "Notebook"
                        },
                        new
                        {
                            Id = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Pack of 10 ballpoint pens",
                            Name = "Pen Set"
                        },
                        new
                        {
                            Id = new Guid("33333333-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Annual Microsoft 365 Business Standard license",
                            Name = "Microsoft 365"
                        },
                        new
                        {
                            Id = new Guid("44444444-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Annual Adobe Creative Cloud all-apps license",
                            Name = "Adobe Creative Cloud"
                        },
                        new
                        {
                            Id = new Guid("55555555-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Annual enterprise antivirus license",
                            Name = "Antivirus"
                        });
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Currency = "USD",
                            Name = "North America"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-cccc-cccc-cccc-cccccccccccc"),
                            Currency = "EUR",
                            Name = "Europe"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-dddd-dddd-dddd-dddddddddddd"),
                            Currency = "EUR",
                            Name = "Lithuania"
                        });
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RejectionCommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RejectionCommentId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RejectionCommentId1");

                    b.HasIndex("RequestTypeId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Requesting a new laptop for the development team",
                            RequestTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequesterId = new Guid("aaaaaaaa-3333-3333-3333-333333333333"),
                            Status = 0,
                            Title = "New Laptop for Development",
                            UpdatedAt = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Monthly office supplies restock for the Vilnius office",
                            RequestTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RequesterId = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            Status = 2,
                            Title = "Office Supplies Restock",
                            UpdatedAt = new DateTime(2025, 1, 16, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 1, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Annual software license renewal for Q1",
                            RequestTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RequesterId = new Guid("aaaaaaaa-3333-3333-3333-333333333333"),
                            Status = 3,
                            Title = "Software Licenses Q1",
                            UpdatedAt = new DateTime(2025, 1, 22, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 2, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Requesting monitor upgrades for the design team",
                            RequestTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RequesterId = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            Status = 1,
                            Title = "Monitor Upgrade",
                            UpdatedAt = new DateTime(2025, 2, 3, 16, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.RequestType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RequestTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "IT Products"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Software & Licenses"
                        });
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.RequesterProduct", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("RequestId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("RequesterProducts");

                    b.HasData(
                        new
                        {
                            RequestId = new Guid("aaaaaaaa-4444-4444-4444-444444444444"),
                            ProductId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Quantity = 1
                        },
                        new
                        {
                            RequestId = new Guid("aaaaaaaa-4444-4444-4444-444444444444"),
                            ProductId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Quantity = 1
                        },
                        new
                        {
                            RequestId = new Guid("aaaaaaaa-4444-4444-4444-444444444444"),
                            ProductId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Quantity = 1
                        },
                        new
                        {
                            RequestId = new Guid("bbbbbbbb-4444-4444-4444-444444444444"),
                            ProductId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Quantity = 5
                        },
                        new
                        {
                            RequestId = new Guid("bbbbbbbb-4444-4444-4444-444444444444"),
                            ProductId = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Quantity = 3
                        },
                        new
                        {
                            RequestId = new Guid("cccccccc-4444-4444-4444-444444444444"),
                            ProductId = new Guid("33333333-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Quantity = 3
                        },
                        new
                        {
                            RequestId = new Guid("cccccccc-4444-4444-4444-444444444444"),
                            ProductId = new Guid("55555555-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Quantity = 3
                        },
                        new
                        {
                            RequestId = new Guid("dddddddd-4444-4444-4444-444444444444"),
                            ProductId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            Name = "Requester"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            Name = "Approver"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-2222-2222-2222-222222222222"),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("ProductRequestType", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "RequestTypeId");

                    b.HasIndex("RequestTypeId");

                    b.ToTable("ProductGroup", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RequestTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ProductId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            RequestTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ProductId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            RequestTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ProductId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            RequestTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ProductId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            RequestTypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ProductId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RequestTypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ProductId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RequestTypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ProductId = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RequestTypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ProductId = new Guid("33333333-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RequestTypeId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ProductId = new Guid("44444444-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RequestTypeId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ProductId = new Guid("55555555-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RequestTypeId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("AccountRole", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Database.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Account", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.ApproverProfile", "ApproverProfile")
                        .WithMany("Accounts")
                        .HasForeignKey("ApproverProfileId");

                    b.HasOne("Infrastructure.Database.Entities.Region", "Region")
                        .WithMany("Accounts")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverProfile");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Comment", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("Infrastructure.Database.Entities.Request", "Request")
                        .WithMany("Comments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Price", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Database.Entities.Region", "Region")
                        .WithMany("Prices")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Request", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Comment", "RejectionComment")
                        .WithMany()
                        .HasForeignKey("RejectionCommentId1");

                    b.HasOne("Infrastructure.Database.Entities.RequestType", "RequestType")
                        .WithMany("Requests")
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Database.Entities.Account", "Requester")
                        .WithMany("Requests")
                        .HasForeignKey("RequesterId");

                    b.Navigation("RejectionComment");

                    b.Navigation("RequestType");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.RequesterProduct", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Product", "Product")
                        .WithMany("RequesterProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Database.Entities.Request", "Request")
                        .WithMany("RequesterProducts")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ProductRequestType", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Database.Entities.RequestType", null)
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Account", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.ApproverProfile", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Product", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("RequesterProducts");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Region", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Request", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("RequesterProducts");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.RequestType", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
