// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504210145_RegionUpdate")]
    partial class RegionUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountRole", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("AccountId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccountRole", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApproverProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApproverProfileId");

                    b.HasIndex("RegionId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.ApproverProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApproverProfiles");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RequestId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Price", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("UnitsOfMeasure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductId", "RegionId");

                    b.HasIndex("RegionId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Standard business laptop for daily work use",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Description = "24-inch Full HD display",
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Description = "Wired USB office keyboard",
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Description = "Wired USB optical mouse",
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Description = "Standard office desk with cable management",
                            Name = "Desk"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Description = "Ergonomic office chair with lumbar support",
                            Name = "Chair"
                        },
                        new
                        {
                            Id = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "A5 lined notebook, pack of 3",
                            Name = "Notebook"
                        },
                        new
                        {
                            Id = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Pack of 10 ballpoint pens",
                            Name = "Pen Set"
                        },
                        new
                        {
                            Id = new Guid("33333333-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Annual Microsoft 365 Business Standard license",
                            Name = "Microsoft 365"
                        },
                        new
                        {
                            Id = new Guid("44444444-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Annual Adobe Creative Cloud all-apps license",
                            Name = "Adobe Creative Cloud"
                        },
                        new
                        {
                            Id = new Guid("55555555-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Annual enterprise antivirus license",
                            Name = "Antivirus"
                        });
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RejectionCommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RejectionCommentId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RejectionCommentId1");

                    b.HasIndex("RequestTypeId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.RequestType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RequestTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "IT Products"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Software & Licenses"
                        });
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.RequesterProduct", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("RequestId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("RequesterProducts");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProductRequestType", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "RequestTypeId");

                    b.HasIndex("RequestTypeId");

                    b.ToTable("ProductGroup", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RequestTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ProductId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            RequestTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ProductId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            RequestTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ProductId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            RequestTypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            ProductId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            RequestTypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ProductId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RequestTypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ProductId = new Guid("11111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RequestTypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ProductId = new Guid("22222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RequestTypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ProductId = new Guid("33333333-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RequestTypeId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ProductId = new Guid("44444444-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RequestTypeId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            ProductId = new Guid("55555555-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RequestTypeId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("AccountRole", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Database.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Account", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.ApproverProfile", "ApproverProfile")
                        .WithMany("Accounts")
                        .HasForeignKey("ApproverProfileId");

                    b.HasOne("Infrastructure.Database.Entities.Region", "Region")
                        .WithMany("Accounts")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverProfile");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Comment", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("Infrastructure.Database.Entities.Request", "Request")
                        .WithMany("Comments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Price", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Database.Entities.Region", "Region")
                        .WithMany("Prices")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Request", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Comment", "RejectionComment")
                        .WithMany()
                        .HasForeignKey("RejectionCommentId1");

                    b.HasOne("Infrastructure.Database.Entities.RequestType", "RequestType")
                        .WithMany("Requests")
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Database.Entities.Account", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId");

                    b.Navigation("RejectionComment");

                    b.Navigation("RequestType");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.RequesterProduct", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Product", "Product")
                        .WithMany("RequesterProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Database.Entities.Request", "Request")
                        .WithMany("RequesterProducts")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ProductRequestType", b =>
                {
                    b.HasOne("Infrastructure.Database.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Database.Entities.RequestType", null)
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.ApproverProfile", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Product", b =>
                {
                    b.Navigation("Prices");

                    b.Navigation("RequesterProducts");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Region", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.Request", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("RequesterProducts");
                });

            modelBuilder.Entity("Infrastructure.Database.Entities.RequestType", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
